version: 2.1

jobs:
  test:
    parameters:
      golang-version:
        type: string
      redis-version:
        type: string
    docker:
      - image: cimg/go:<< parameters.golang-version >>
      - image: cimg/redis:<< parameters.redis-version >>
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
      - run: sudo apt-get update && sudo apt-get install -y time redis-tools
      - run: while ! redis-cli ping 2>/dev/null ; do sleep 1 ; done
      - run: .circleci/circle_build.sh

workflows:
  test-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              golang-version:
                - '1.18'
                - '1.19'
              redis-version:
                - '5.0'
                - '6.0'
                - '7.0'
